version: "3.9"

services:
    # Application
    ecommerce-app:
        build: .
        container_name: ecommerce-app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - .:/usr/src/app
        env_file:
          - core/.env
        ports:
          - "8000:8000"
        depends_on:
          - ecommerce-db
    # Database
    ecommerce-db:
        image: postgres
        container_name: ecommerce-db
        volumes:
          - pgdata:/var/lib/postgresql/data/
        env_file:
          - core/.env
volumes:
    pgdata: